#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 11sumikaito
# SPDX-License-Identifier: BSD-3-Clause

import sys

def print_world_cup_winner(year):
    try:
        with open('world_cup_winner.txt', 'r', encoding='utf-8') as file:
            data = {}
            for line in file:
                parts = line.strip().split(',')
                if len(parts) == 2:
                    current_year, winner = parts
                    data[current_year] = winner

            if year in data:
                print(f"{year}年のワールドカップ優勝国は {data[year]} です。")
            else:
                print(f"{year}年の該当する年代のデータが見つかりませんでした。")

    except FileNotFoundError:
        print("指定されたファイルが見つかりませんでした")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("正しい引数がありません。使用法: python3 world_cup_winner.py <年数>")
        sys.exit(1)

    user_input = sys.argv[1]
    print_world_cup_winner(user_input)
