name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: All test
      run: bash ./test.bash
     - name: All test
      run: bash ./test.bash
